"""add employees table and employee_id to bookings

Revision ID: 0c69562e3747
Revises: 56868763ad66
Create Date: 2025-12-06 16:14:31.812635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c69562e3747'
down_revision: Union[str, None] = '56868763ad66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_business_id'), 'employees', ['business_id'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.add_column('bookings', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bookings_employee_id'), 'bookings', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_employee_id'), table_name='bookings')
    op.drop_column('bookings', 'employee_id')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_business_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
