"""add gender and avatar_url to users

Revision ID: 7ee7828769b2
Revises: 3b58f4b7fc83
Create Date: 2025-12-27 20:33:10.664925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee7828769b2'
down_revision: Union[str, None] = '3b58f4b7fc83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create gender enum type
    gender_enum = sa.Enum('male', 'female', 'other', name='gender')
    gender_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('gender', gender_enum, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'gender')

    # Drop gender enum type
    sa.Enum(name='gender').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
