"""add business_photos table

Revision ID: 56868763ad66
Revises: c97520c5c19a
Create Date: 2025-12-06 15:56:32.314530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56868763ad66'
down_revision: Union[str, None] = 'c97520c5c19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_photos_business_id'), 'business_photos', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_photos_id'), 'business_photos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_photos_id'), table_name='business_photos')
    op.drop_index(op.f('ix_business_photos_business_id'), table_name='business_photos')
    op.drop_table('business_photos')
    # ### end Alembic commands ###
